### PR TITLE
Fix elixir 1.4 warnings

### PR DESCRIPTION
**Pull request by novaugust**
- update exprintf dep to remove its warnings
- replace deprecated Dict.get with Map.get or Keyword.get as appropriate
- replace defp headers with @headers module attribute
- add parens to 0 param function calls in mix.exs
- add description to project config in mix.exs
- update readme with new github user

### CODE REVIEW

**Comment by novaugust** [comment]
Looks like a new coveralls needs to be made for the new repo

**Comment by nilsivanson** [comment]
Can we merge this? What is the status of maintenance of this project?

**Comment by novaugust** [comment]
@nivanson 
> Can we merge this? What is the status of maintenance of this project?

Last commit December '16 :/ We're just pointing at my fork over here..
https://github.com/novaugust/zenixir/tree/elixir-1.4

**Comment by nivanson** [comment]
I am running this in production on a small business. What is your status?

**Pull request closed without merging**
